steps:
  # Build the container image using Build-Args
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/${PROJECT_ID}/safestay'
      - '--build-arg'
      - '_VITE_GEMINI_API_KEY=${_VITE_GEMINI_API_KEY}'
      - '--build-arg'
      - '_VITE_FIREBASE_API_KEY=${_VITE_FIREBASE_API_KEY}'
      - '--build-arg'
      - '_VITE_FIREBASE_AUTH_DOMAIN=${_VITE_FIREBASE_AUTH_DOMAIN}'
      - '--build-arg'
      - '_VITE_FIREBASE_PROJECT_ID=${_VITE_FIREBASE_PROJECT_ID}'
      - '--build-arg'
      - '_VITE_FIREBASE_STORAGE_BUCKET=${_VITE_FIREBASE_STORAGE_BUCKET}'
      - '--build-arg'
      - '_VITE_FIREBASE_MESSAGING_SENDER_ID=${_VITE_FIREBASE_MESSAGING_SENDER_ID}'
      - '--build-arg'
      - '_VITE_FIREBASE_APP_ID=${_VITE_FIREBASE_APP_ID}'
      - '--build-arg'
      - '_VITE_FIREBASE_MEASUREMENT_ID=${_VITE_FIREBASE_MEASUREMENT_ID}'
      - '.'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/safestay']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'staysafe'
      - '--image'
      - 'gcr.io/${PROJECT_ID}/safestay'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/${PROJECT_ID}/safestay'
